FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["BookmasterAPI/BookmasterAPI.csproj", "BookmasterAPI/"]
COPY ["Persistence/Persistence.csproj", "Persistence/"]
COPY ["Application/Application.csproj", "Application/"]
COPY ["Domain/Domain.csproj", "Domain/"]
RUN dotnet restore "BookmasterAPI/BookmasterAPI.csproj"
COPY . .
WORKDIR "/src/BookmasterAPI"
RUN dotnet build "BookmasterAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BookmasterAPI.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BookmasterAPI.dll"]