version: '3.8'
services:
  postgres.db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: BookmasterDB
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
